### ISSUE TITLE
Nội dung mail hiện dạng html

### ISSUE THREAD

**Issue by iamquang95** [ngthanhtrung23/vnoiwebsite#49]
![mail](https://cloud.githubusercontent.com/assets/8794293/7220198/3733c712-e6e9-11e4-88a3-55ff73a731b9.PNG)

<p>This is content</p>

**Comment by ngthanhtrung23** [comment]
I'm working on this.
btw, please use English on Github :dancer:

**Comment by ngthanhtrung23** [comment]
This should be fixed now.
